//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Detai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class about
    {
        public int id { get; set; }
        public string img { get; set; }
        public string title { get; set; }
        public string name { get; set; }
        public string detail { get; set; }
        public string linkfb { get; set; }
        public string linkig { get; set; }
        public string linktwitter { get; set; }
    }
}
